// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'src/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 481047032094263803),
    name: 'Ammo',
    lastPropertyId: const obx_int.IdUid(39, 2696625425089428654),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2901007259994632443),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4892552665044215911),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 944814867517340877),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 56589591724136369),
        name: 'caliber',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7435866408476540470),
        name: 'weight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7749662423289089179),
        name: 'length',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8466745873890719630),
        name: 'dragTypeValue',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3597551566518548180),
        name: 'bcG1',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7303427883357653560),
        name: 'bcG7',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4419156203835689908),
        name: 'useMultiBcG1',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6354716405896547240),
        name: 'useMultiBcG7',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2492064189372607551),
        name: 'muzzleVelocity',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5514844413031348455),
        name: 'muzzleVelocityTemperature',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1799365847783643769),
        name: 'powderTemperature',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 974272242678895264),
        name: 'powderSensitivity',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8929423509273604592),
        name: 'powderSensitivityTemperatures',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 3283350237107193853),
        name: 'powderSensitivityVelocities',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 6833671569938414681),
        name: 'multiBcTableG1Mv',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 1770810788819588875),
        name: 'multiBcTableG1Bc',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 5416477658534681004),
        name: 'multiBcTableG7Mv',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 1495083720739637525),
        name: 'multiBcTableG7Bc',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 7530323202461384488),
        name: 'cusomDragTableV',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 634242907511084069),
        name: 'cusomDragTableCd',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 2599773404316424628),
        name: 'zeroDistance',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 3473906109131868875),
        name: 'zeroLookAngle',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 6170586545303640674),
        name: 'zeroTemperature',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 1331174537811421704),
        name: 'zeroPressure',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 5088462136301972979),
        name: 'zeroHumidity',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 9201312319250354552),
        name: 'zeroPowdertemperature',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 8205752393931719157),
        name: 'usePowderSensitivity',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 1913627030764324238),
        name: 'zeroUseDiffPowderTemperature',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 1907733704559307991),
        name: 'zeroUseCoriolis',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(32, 6747201973793974182),
        name: 'zerolatitudeDeg',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 2977679308571644561),
        name: 'zeroAzimuthDeg',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(34, 4581674611466032688),
        name: 'zeroOffsetX',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(35, 4437029025770366401),
        name: 'zeroOffsetY',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(36, 2792708475255283450),
        name: 'projectileName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(37, 5801824058910442871),
        name: 'vendor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(38, 7638575890122222855),
        name: 'image',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(39, 2696625425089428654),
        name: 'ownerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 1414798269651944252),
        relationField: 'owner',
        relationTarget: 'Owner',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'profiles',
        srcEntity: 'Profile',
        srcField: 'ammo',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3319446897955563326),
    name: 'ConvertorsState',
    lastPropertyId: const obx_int.IdUid(17, 8290030605337265686),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8210313356350926060),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6771566658215870639),
        name: 'lengthValueInch',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4025591754516451395),
        name: 'lengthUnit',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1951570794484611444),
        name: 'weightValueGrain',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8509556449611080162),
        name: 'weight',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6621825253328128572),
        name: 'pressureValueMmHg',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 811841300633756386),
        name: 'pressure',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6400710630634493678),
        name: 'temperatureValueFahrenheit',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1306657369725317903),
        name: 'temperature',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3521516380372782062),
        name: 'torqueValueNewtonMeter',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1338303344777086487),
        name: 'torque',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 351391817273593368),
        name: 'anglesConvertorDistanceValueMeter',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 623798383099068972),
        name: 'anglesConvertorDistance',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3384127170950481517),
        name: 'anglesConvertorAngularValueMil',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8478334701850613082),
        name: 'anglesConvertorAngular',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8256106710858315457),
        name: 'anglesConvertorOutput',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 8290030605337265686),
        name: 'ownerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 5622245447060915548),
        relationField: 'owner',
        relationTarget: 'Owner',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8073167112424079668),
    name: 'GeneralSettings',
    lastPropertyId: const obx_int.IdUid(14, 9052054885912932392),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8791359397735324035),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7804057525880621514),
        name: 'languageCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 453581952653100111),
        name: 'themeMode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4438040467716406984),
        name: 'adjustmentDisplayFormatValue',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1673671360262079089),
        name: 'homeShowMil',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6513508670694402455),
        name: 'homeShowMrad',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3843607747392870150),
        name: 'homeShowMoa',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1496502728118112879),
        name: 'homeShowCmPer100m',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8265756595400664844),
        name: 'homeShowInPer100yd',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8149215468390085119),
        name: 'homeChartDistanceStep',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7582766058255469157),
        name: 'homeTableDistanceStep',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4643998212685076016),
        name: 'homeShowSubsonicTransition',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3711858234252380760),
        name: 'activeProfileId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 8499428017894885351),
        relationField: 'activeProfile',
        relationTarget: 'Profile',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 9052054885912932392),
        name: 'ownerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 5387131100306356366),
        relationField: 'owner',
        relationTarget: 'Owner',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 4146065780846629425),
    name: 'Owner',
    lastPropertyId: const obx_int.IdUid(2, 5792398024273257746),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4764573206261776736),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5792398024273257746),
        name: 'token',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 4697863759429240582),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'sights',
        srcEntity: 'Sight',
        srcField: 'owner',
      ),
      obx_int.ModelBacklink(
        name: 'cartridges',
        srcEntity: 'Ammo',
        srcField: 'owner',
      ),
      obx_int.ModelBacklink(
        name: 'profiles',
        srcEntity: 'Profile',
        srcField: 'owner',
      ),
      obx_int.ModelBacklink(
        name: 'generalSettings',
        srcEntity: 'GeneralSettings',
        srcField: 'owner',
      ),
      obx_int.ModelBacklink(
        name: 'unitSettings',
        srcEntity: 'UnitSettings',
        srcField: 'owner',
      ),
      obx_int.ModelBacklink(
        name: 'tablesSettings',
        srcEntity: 'TablesSettings',
        srcField: 'owner',
      ),
      obx_int.ModelBacklink(
        name: 'convertorsState',
        srcEntity: 'ConvertorsState',
        srcField: 'owner',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 5490667085782347020),
    name: 'Profile',
    lastPropertyId: const obx_int.IdUid(6, 4262110574303383529),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2606131867070314293),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5269928524214625478),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 3984776485633185038),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2799668789915472983),
        name: 'weaponId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(8, 8935048605143841354),
        relationField: 'weapon',
        relationTarget: 'Weapon',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7674099467332995723),
        name: 'sightId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(9, 3198040514221949665),
        relationField: 'sight',
        relationTarget: 'Sight',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4934311954558672616),
        name: 'ammoId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(10, 8947069842433100647),
        relationField: 'ammo',
        relationTarget: 'Ammo',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4262110574303383529),
        name: 'ownerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(11, 8484758124775365437),
        relationField: 'owner',
        relationTarget: 'Owner',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 9008070843231077690),
    name: 'Sight',
    lastPropertyId: const obx_int.IdUid(16, 737672345032110523),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 919847119481515594),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1266146636472715629),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(12, 3349502908616485721),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4730951943852551568),
        name: 'focalPlaneValue',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1437704715851296309),
        name: 'sightHeight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4348750242276057672),
        name: 'verticalClick',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7133568171093229424),
        name: 'horizontalClick',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8556256170433879895),
        name: 'verticalClickUnit',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8415923395606248925),
        name: 'horizontalClickUnit',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3906981019707090664),
        name: 'sightHorizontalOffset',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4265494260285088797),
        name: 'minMagnification',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5927275518010705589),
        name: 'maxMagnification',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 9118290778744932374),
        name: 'reticleImage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8741917341393131758),
        name: 'vendor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8564399592138595318),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5148724877052041991),
        name: 'image',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 737672345032110523),
        name: 'ownerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(13, 3513124015476916633),
        relationField: 'owner',
        relationTarget: 'Owner',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'profiles',
        srcEntity: 'Profile',
        srcField: 'sight',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 1704755846093761912),
    name: 'TablesSettings',
    lastPropertyId: const obx_int.IdUid(9, 7685983959523799065),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3904112876819047042),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7130419408238951888),
        name: 'distanceStart',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 462378690113141369),
        name: 'distanceEnd',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4571615005069247360),
        name: 'distanceStep',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5752190580816842465),
        name: 'showZeros',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8086465214496480259),
        name: 'showSubsonicTransition',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1547267455747564243),
        name: 'hiddenCols',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8454924801350945338),
        name: 'hiddenAdjustmentCols',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7685983959523799065),
        name: 'ownerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(14, 8530595160478793144),
        relationField: 'owner',
        relationTarget: 'Owner',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 7409307519479360238),
    name: 'UnitSettings',
    lastPropertyId: const obx_int.IdUid(18, 1589305927285534260),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2574261671122380397),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8190374573504699068),
        name: 'angular',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 721470034526528927),
        name: 'distance',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1950823500597381018),
        name: 'velocity',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3189248578133516861),
        name: 'pressure',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4016752690686672589),
        name: 'temperature',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2448712547617322053),
        name: 'diameter',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1040531279054683834),
        name: 'length',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8735993121549846756),
        name: 'weight',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1432995802985942385),
        name: 'adjustment',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7183764841033346823),
        name: 'drop',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4574191807868244823),
        name: 'energy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 957184778541887085),
        name: 'sightHeight',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 310378686667290309),
        name: 'twist',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8967602202400780550),
        name: 'barrelLength',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 5854393186863005947),
        name: 'time',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 4797208469546747566),
        name: 'torque',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 1589305927285534260),
        name: 'ownerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(15, 5972717579111743737),
        relationField: 'owner',
        relationTarget: 'Owner',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 1731139601222753801),
    name: 'Weapon',
    lastPropertyId: const obx_int.IdUid(8, 2042548101712427756),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6774292354499432759),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3422866154256838854),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(16, 8111909717702429569),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6368953314469303965),
        name: 'caliber',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6284527265072016857),
        name: 'twist',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6255307954200195809),
        name: 'barrelLength',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6666126699331535385),
        name: 'vendor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4415277081708050689),
        name: 'image',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2042548101712427756),
        name: 'ownerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(17, 9049041270276597027),
        relationField: 'owner',
        relationTarget: 'Owner',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(9, 1731139601222753801),
    lastIndexId: const obx_int.IdUid(17, 9049041270276597027),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Ammo: obx_int.EntityDefinition<Ammo>(
      model: _entities[0],
      toOneRelations: (Ammo object) => [object.owner],
      toManyRelations: (Ammo object) => {
        obx_int.RelInfo<Profile>.toOneBacklink(
          5,
          object.id,
          (Profile srcObject) => srcObject.ammo,
        ): object.profiles,
      },
      getId: (Ammo object) => object.id,
      setId: (Ammo object, int id) {
        object.id = id;
      },
      objectToFB: (Ammo object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final dragTypeValueOffset = fbb.writeString(object.dragTypeValue);
        final powderSensitivityTemperaturesOffset =
            object.powderSensitivityTemperatures == null
            ? null
            : fbb.writeListFloat64(object.powderSensitivityTemperatures!);
        final powderSensitivityVelocitiesOffset =
            object.powderSensitivityVelocities == null
            ? null
            : fbb.writeListFloat64(object.powderSensitivityVelocities!);
        final multiBcTableG1MvOffset = object.multiBcTableG1Mv == null
            ? null
            : fbb.writeListFloat64(object.multiBcTableG1Mv!);
        final multiBcTableG1BcOffset = object.multiBcTableG1Bc == null
            ? null
            : fbb.writeListFloat64(object.multiBcTableG1Bc!);
        final multiBcTableG7MvOffset = object.multiBcTableG7Mv == null
            ? null
            : fbb.writeListFloat64(object.multiBcTableG7Mv!);
        final multiBcTableG7BcOffset = object.multiBcTableG7Bc == null
            ? null
            : fbb.writeListFloat64(object.multiBcTableG7Bc!);
        final cusomDragTableVOffset = object.cusomDragTableV == null
            ? null
            : fbb.writeListFloat64(object.cusomDragTableV!);
        final cusomDragTableCdOffset = object.cusomDragTableCd == null
            ? null
            : fbb.writeListFloat64(object.cusomDragTableCd!);
        final projectileNameOffset = object.projectileName == null
            ? null
            : fbb.writeString(object.projectileName!);
        final vendorOffset = object.vendor == null
            ? null
            : fbb.writeString(object.vendor!);
        final imageOffset = object.image == null
            ? null
            : fbb.writeString(object.image!);
        fbb.startTable(40);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.caliber);
        fbb.addFloat64(3, object.weight);
        fbb.addFloat64(4, object.length);
        fbb.addOffset(5, dragTypeValueOffset);
        fbb.addFloat64(6, object.bcG1);
        fbb.addFloat64(7, object.bcG7);
        fbb.addBool(8, object.useMultiBcG1);
        fbb.addBool(9, object.useMultiBcG7);
        fbb.addFloat64(10, object.muzzleVelocity);
        fbb.addFloat64(11, object.muzzleVelocityTemperature);
        fbb.addFloat64(12, object.powderTemperature);
        fbb.addFloat64(13, object.powderSensitivity);
        fbb.addOffset(14, powderSensitivityTemperaturesOffset);
        fbb.addOffset(15, powderSensitivityVelocitiesOffset);
        fbb.addOffset(16, multiBcTableG1MvOffset);
        fbb.addOffset(17, multiBcTableG1BcOffset);
        fbb.addOffset(18, multiBcTableG7MvOffset);
        fbb.addOffset(19, multiBcTableG7BcOffset);
        fbb.addOffset(20, cusomDragTableVOffset);
        fbb.addOffset(21, cusomDragTableCdOffset);
        fbb.addFloat64(22, object.zeroDistance);
        fbb.addFloat64(23, object.zeroLookAngle);
        fbb.addFloat64(24, object.zeroTemperature);
        fbb.addFloat64(25, object.zeroPressure);
        fbb.addFloat64(26, object.zeroHumidity);
        fbb.addFloat64(27, object.zeroPowdertemperature);
        fbb.addBool(28, object.usePowderSensitivity);
        fbb.addBool(29, object.zeroUseDiffPowderTemperature);
        fbb.addBool(30, object.zeroUseCoriolis);
        fbb.addFloat64(31, object.zerolatitudeDeg);
        fbb.addFloat64(32, object.zeroAzimuthDeg);
        fbb.addFloat64(33, object.zeroOffsetX);
        fbb.addFloat64(34, object.zeroOffsetY);
        fbb.addOffset(35, projectileNameOffset);
        fbb.addOffset(36, vendorOffset);
        fbb.addOffset(37, imageOffset);
        fbb.addInt64(38, object.owner.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Ammo()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..caliber = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..weight = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..length = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..dragTypeValue = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..bcG1 = const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0)
          ..bcG7 = const fb.Float64Reader().vTableGet(buffer, rootOffset, 18, 0)
          ..useMultiBcG1 = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            20,
            false,
          )
          ..useMultiBcG7 = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            22,
            false,
          )
          ..muzzleVelocity = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            24,
          )
          ..muzzleVelocityTemperature = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            26,
            0,
          )
          ..powderTemperature = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            28,
            0,
          )
          ..powderSensitivity = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            30,
            0,
          )
          ..powderSensitivityTemperatures = const obx_int.Float64ListReader()
              .vTableGetNullable(buffer, rootOffset, 32)
          ..powderSensitivityVelocities = const obx_int.Float64ListReader()
              .vTableGetNullable(buffer, rootOffset, 34)
          ..multiBcTableG1Mv = const obx_int.Float64ListReader()
              .vTableGetNullable(buffer, rootOffset, 36)
          ..multiBcTableG1Bc = const obx_int.Float64ListReader()
              .vTableGetNullable(buffer, rootOffset, 38)
          ..multiBcTableG7Mv = const obx_int.Float64ListReader()
              .vTableGetNullable(buffer, rootOffset, 40)
          ..multiBcTableG7Bc = const obx_int.Float64ListReader()
              .vTableGetNullable(buffer, rootOffset, 42)
          ..cusomDragTableV = const obx_int.Float64ListReader()
              .vTableGetNullable(buffer, rootOffset, 44)
          ..cusomDragTableCd = const obx_int.Float64ListReader()
              .vTableGetNullable(buffer, rootOffset, 46)
          ..zeroDistance = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            48,
            0,
          )
          ..zeroLookAngle = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            50,
            0,
          )
          ..zeroTemperature = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            52,
            0,
          )
          ..zeroPressure = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            54,
            0,
          )
          ..zeroHumidity = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            56,
            0,
          )
          ..zeroPowdertemperature = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            58,
            0,
          )
          ..usePowderSensitivity = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            60,
            false,
          )
          ..zeroUseDiffPowderTemperature = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            62,
            false,
          )
          ..zeroUseCoriolis = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            64,
            false,
          )
          ..zerolatitudeDeg = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            66,
          )
          ..zeroAzimuthDeg = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            68,
          )
          ..zeroOffsetX = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            70,
            0,
          )
          ..zeroOffsetY = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            72,
            0,
          )
          ..projectileName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 74)
          ..vendor = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 76)
          ..image = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 78);
        object.owner.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          80,
          0,
        );
        object.owner.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Ammo>(
          object.profiles,
          store,
          obx_int.RelInfo<Profile>.toOneBacklink(
            5,
            object.id,
            (Profile srcObject) => srcObject.ammo,
          ),
        );
        return object;
      },
    ),
    ConvertorsState: obx_int.EntityDefinition<ConvertorsState>(
      model: _entities[1],
      toOneRelations: (ConvertorsState object) => [object.owner],
      toManyRelations: (ConvertorsState object) => {},
      getId: (ConvertorsState object) => object.id,
      setId: (ConvertorsState object, int id) {
        object.id = id;
      },
      objectToFB: (ConvertorsState object, fb.Builder fbb) {
        final lengthUnitOffset = fbb.writeString(object.lengthUnit);
        final weightOffset = fbb.writeString(object.weight);
        final pressureOffset = fbb.writeString(object.pressure);
        final temperatureOffset = fbb.writeString(object.temperature);
        final torqueOffset = fbb.writeString(object.torque);
        final anglesConvertorDistanceOffset = fbb.writeString(
          object.anglesConvertorDistance,
        );
        final anglesConvertorAngularOffset = fbb.writeString(
          object.anglesConvertorAngular,
        );
        final anglesConvertorOutputOffset = fbb.writeString(
          object.anglesConvertorOutput,
        );
        fbb.startTable(18);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.lengthValueInch);
        fbb.addOffset(2, lengthUnitOffset);
        fbb.addFloat64(3, object.weightValueGrain);
        fbb.addOffset(4, weightOffset);
        fbb.addFloat64(5, object.pressureValueMmHg);
        fbb.addOffset(6, pressureOffset);
        fbb.addFloat64(7, object.temperatureValueFahrenheit);
        fbb.addOffset(8, temperatureOffset);
        fbb.addFloat64(9, object.torqueValueNewtonMeter);
        fbb.addOffset(10, torqueOffset);
        fbb.addFloat64(11, object.anglesConvertorDistanceValueMeter);
        fbb.addOffset(12, anglesConvertorDistanceOffset);
        fbb.addFloat64(13, object.anglesConvertorAngularValueMil);
        fbb.addOffset(14, anglesConvertorAngularOffset);
        fbb.addOffset(15, anglesConvertorOutputOffset);
        fbb.addInt64(16, object.owner.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ConvertorsState()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..lengthValueInch = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..lengthUnit = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..weightValueGrain = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..weight = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..pressureValueMmHg = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..pressure = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..temperatureValueFahrenheit = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..temperature = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..torqueValueNewtonMeter = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            22,
            0,
          )
          ..torque = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 24, '')
          ..anglesConvertorDistanceValueMeter = const fb.Float64Reader()
              .vTableGet(buffer, rootOffset, 26, 0)
          ..anglesConvertorDistance = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 28, '')
          ..anglesConvertorAngularValueMil = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            30,
            0,
          )
          ..anglesConvertorAngular = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 32, '')
          ..anglesConvertorOutput = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 34, '');
        object.owner.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        object.owner.attach(store);
        return object;
      },
    ),
    GeneralSettings: obx_int.EntityDefinition<GeneralSettings>(
      model: _entities[2],
      toOneRelations: (GeneralSettings object) => [
        object.activeProfile,
        object.owner,
      ],
      toManyRelations: (GeneralSettings object) => {},
      getId: (GeneralSettings object) => object.id,
      setId: (GeneralSettings object, int id) {
        object.id = id;
      },
      objectToFB: (GeneralSettings object, fb.Builder fbb) {
        final languageCodeOffset = fbb.writeString(object.languageCode);
        final themeModeOffset = fbb.writeString(object.themeMode);
        final adjustmentDisplayFormatValueOffset = fbb.writeString(
          object.adjustmentDisplayFormatValue,
        );
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, languageCodeOffset);
        fbb.addOffset(2, themeModeOffset);
        fbb.addOffset(3, adjustmentDisplayFormatValueOffset);
        fbb.addBool(4, object.homeShowMil);
        fbb.addBool(5, object.homeShowMrad);
        fbb.addBool(6, object.homeShowMoa);
        fbb.addBool(7, object.homeShowCmPer100m);
        fbb.addBool(8, object.homeShowInPer100yd);
        fbb.addFloat64(9, object.homeChartDistanceStep);
        fbb.addFloat64(10, object.homeTableDistanceStep);
        fbb.addBool(11, object.homeShowSubsonicTransition);
        fbb.addInt64(12, object.activeProfile.targetId);
        fbb.addInt64(13, object.owner.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = GeneralSettings()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..languageCode = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..themeMode = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..adjustmentDisplayFormatValue = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..homeShowMil = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            12,
            false,
          )
          ..homeShowMrad = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            14,
            false,
          )
          ..homeShowMoa = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            16,
            false,
          )
          ..homeShowCmPer100m = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            18,
            false,
          )
          ..homeShowInPer100yd = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            20,
            false,
          )
          ..homeChartDistanceStep = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            22,
            0,
          )
          ..homeTableDistanceStep = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            24,
            0,
          )
          ..homeShowSubsonicTransition = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            26,
            false,
          );
        object.activeProfile.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        object.activeProfile.attach(store);
        object.owner.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        object.owner.attach(store);
        return object;
      },
    ),
    Owner: obx_int.EntityDefinition<Owner>(
      model: _entities[3],
      toOneRelations: (Owner object) => [],
      toManyRelations: (Owner object) => {
        obx_int.RelInfo<Sight>.toOneBacklink(
          16,
          object.id,
          (Sight srcObject) => srcObject.owner,
        ): object.sights,
        obx_int.RelInfo<Ammo>.toOneBacklink(
          39,
          object.id,
          (Ammo srcObject) => srcObject.owner,
        ): object.cartridges,
        obx_int.RelInfo<Profile>.toOneBacklink(
          6,
          object.id,
          (Profile srcObject) => srcObject.owner,
        ): object.profiles,
        obx_int.RelInfo<GeneralSettings>.toOneBacklink(
          14,
          object.id,
          (GeneralSettings srcObject) => srcObject.owner,
        ): object.generalSettings,
        obx_int.RelInfo<UnitSettings>.toOneBacklink(
          18,
          object.id,
          (UnitSettings srcObject) => srcObject.owner,
        ): object.unitSettings,
        obx_int.RelInfo<TablesSettings>.toOneBacklink(
          9,
          object.id,
          (TablesSettings srcObject) => srcObject.owner,
        ): object.tablesSettings,
        obx_int.RelInfo<ConvertorsState>.toOneBacklink(
          17,
          object.id,
          (ConvertorsState srcObject) => srcObject.owner,
        ): object.convertorsState,
      },
      getId: (Owner object) => object.id,
      setId: (Owner object, int id) {
        object.id = id;
      },
      objectToFB: (Owner object, fb.Builder fbb) {
        final tokenOffset = object.token == null
            ? null
            : fbb.writeString(object.token!);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, tokenOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Owner()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..token = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 6);
        obx_int.InternalToManyAccess.setRelInfo<Owner>(
          object.sights,
          store,
          obx_int.RelInfo<Sight>.toOneBacklink(
            16,
            object.id,
            (Sight srcObject) => srcObject.owner,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Owner>(
          object.cartridges,
          store,
          obx_int.RelInfo<Ammo>.toOneBacklink(
            39,
            object.id,
            (Ammo srcObject) => srcObject.owner,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Owner>(
          object.profiles,
          store,
          obx_int.RelInfo<Profile>.toOneBacklink(
            6,
            object.id,
            (Profile srcObject) => srcObject.owner,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Owner>(
          object.generalSettings,
          store,
          obx_int.RelInfo<GeneralSettings>.toOneBacklink(
            14,
            object.id,
            (GeneralSettings srcObject) => srcObject.owner,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Owner>(
          object.unitSettings,
          store,
          obx_int.RelInfo<UnitSettings>.toOneBacklink(
            18,
            object.id,
            (UnitSettings srcObject) => srcObject.owner,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Owner>(
          object.tablesSettings,
          store,
          obx_int.RelInfo<TablesSettings>.toOneBacklink(
            9,
            object.id,
            (TablesSettings srcObject) => srcObject.owner,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<Owner>(
          object.convertorsState,
          store,
          obx_int.RelInfo<ConvertorsState>.toOneBacklink(
            17,
            object.id,
            (ConvertorsState srcObject) => srcObject.owner,
          ),
        );
        return object;
      },
    ),
    Profile: obx_int.EntityDefinition<Profile>(
      model: _entities[4],
      toOneRelations: (Profile object) => [
        object.weapon,
        object.sight,
        object.ammo,
        object.owner,
      ],
      toManyRelations: (Profile object) => {},
      getId: (Profile object) => object.id,
      setId: (Profile object, int id) {
        object.id = id;
      },
      objectToFB: (Profile object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.weapon.targetId);
        fbb.addInt64(3, object.sight.targetId);
        fbb.addInt64(4, object.ammo.targetId);
        fbb.addInt64(5, object.owner.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Profile()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '');
        object.weapon.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.weapon.attach(store);
        object.sight.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.sight.attach(store);
        object.ammo.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.ammo.attach(store);
        object.owner.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.owner.attach(store);
        return object;
      },
    ),
    Sight: obx_int.EntityDefinition<Sight>(
      model: _entities[5],
      toOneRelations: (Sight object) => [object.owner],
      toManyRelations: (Sight object) => {
        obx_int.RelInfo<Profile>.toOneBacklink(
          4,
          object.id,
          (Profile srcObject) => srcObject.sight,
        ): object.profiles,
      },
      getId: (Sight object) => object.id,
      setId: (Sight object, int id) {
        object.id = id;
      },
      objectToFB: (Sight object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final focalPlaneValueOffset = fbb.writeString(object.focalPlaneValue);
        final verticalClickUnitOffset = fbb.writeString(
          object.verticalClickUnit,
        );
        final horizontalClickUnitOffset = fbb.writeString(
          object.horizontalClickUnit,
        );
        final reticleImageOffset = object.reticleImage == null
            ? null
            : fbb.writeString(object.reticleImage!);
        final vendorOffset = object.vendor == null
            ? null
            : fbb.writeString(object.vendor!);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final imageOffset = object.image == null
            ? null
            : fbb.writeString(object.image!);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, focalPlaneValueOffset);
        fbb.addFloat64(3, object.sightHeight);
        fbb.addFloat64(4, object.verticalClick);
        fbb.addFloat64(5, object.horizontalClick);
        fbb.addOffset(6, verticalClickUnitOffset);
        fbb.addOffset(7, horizontalClickUnitOffset);
        fbb.addFloat64(8, object.sightHorizontalOffset);
        fbb.addFloat64(9, object.minMagnification);
        fbb.addFloat64(10, object.maxMagnification);
        fbb.addOffset(11, reticleImageOffset);
        fbb.addOffset(12, vendorOffset);
        fbb.addOffset(13, notesOffset);
        fbb.addOffset(14, imageOffset);
        fbb.addInt64(15, object.owner.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Sight()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..focalPlaneValue = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..sightHeight = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..verticalClick = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..horizontalClick = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..verticalClickUnit = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..horizontalClickUnit = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '')
          ..sightHorizontalOffset = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          )
          ..minMagnification = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            22,
            0,
          )
          ..maxMagnification = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            24,
            0,
          )
          ..reticleImage = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 26)
          ..vendor = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 28)
          ..notes = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 30)
          ..image = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 32);
        object.owner.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          34,
          0,
        );
        object.owner.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Sight>(
          object.profiles,
          store,
          obx_int.RelInfo<Profile>.toOneBacklink(
            4,
            object.id,
            (Profile srcObject) => srcObject.sight,
          ),
        );
        return object;
      },
    ),
    TablesSettings: obx_int.EntityDefinition<TablesSettings>(
      model: _entities[6],
      toOneRelations: (TablesSettings object) => [object.owner],
      toManyRelations: (TablesSettings object) => {},
      getId: (TablesSettings object) => object.id,
      setId: (TablesSettings object, int id) {
        object.id = id;
      },
      objectToFB: (TablesSettings object, fb.Builder fbb) {
        final hiddenColsOffset = fbb.writeList(
          object.hiddenCols.map(fbb.writeString).toList(growable: false),
        );
        final hiddenAdjustmentColsOffset = fbb.writeList(
          object.hiddenAdjustmentCols
              .map(fbb.writeString)
              .toList(growable: false),
        );
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.distanceStart);
        fbb.addFloat64(2, object.distanceEnd);
        fbb.addFloat64(3, object.distanceStep);
        fbb.addBool(4, object.showZeros);
        fbb.addBool(5, object.showSubsonicTransition);
        fbb.addOffset(6, hiddenColsOffset);
        fbb.addOffset(7, hiddenAdjustmentColsOffset);
        fbb.addInt64(8, object.owner.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = TablesSettings()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..distanceStart = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..distanceEnd = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..distanceStep = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..showZeros = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            12,
            false,
          )
          ..showSubsonicTransition = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            14,
            false,
          )
          ..hiddenCols = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 16, [])
          ..hiddenAdjustmentCols = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 18, []);
        object.owner.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.owner.attach(store);
        return object;
      },
    ),
    UnitSettings: obx_int.EntityDefinition<UnitSettings>(
      model: _entities[7],
      toOneRelations: (UnitSettings object) => [object.owner],
      toManyRelations: (UnitSettings object) => {},
      getId: (UnitSettings object) => object.id,
      setId: (UnitSettings object, int id) {
        object.id = id;
      },
      objectToFB: (UnitSettings object, fb.Builder fbb) {
        final angularOffset = fbb.writeString(object.angular);
        final distanceOffset = fbb.writeString(object.distance);
        final velocityOffset = fbb.writeString(object.velocity);
        final pressureOffset = fbb.writeString(object.pressure);
        final temperatureOffset = fbb.writeString(object.temperature);
        final diameterOffset = fbb.writeString(object.diameter);
        final lengthOffset = fbb.writeString(object.length);
        final weightOffset = fbb.writeString(object.weight);
        final adjustmentOffset = fbb.writeString(object.adjustment);
        final dropOffset = fbb.writeString(object.drop);
        final energyOffset = fbb.writeString(object.energy);
        final sightHeightOffset = fbb.writeString(object.sightHeight);
        final twistOffset = fbb.writeString(object.twist);
        final barrelLengthOffset = fbb.writeString(object.barrelLength);
        final timeOffset = fbb.writeString(object.time);
        final torqueOffset = fbb.writeString(object.torque);
        fbb.startTable(19);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, angularOffset);
        fbb.addOffset(2, distanceOffset);
        fbb.addOffset(3, velocityOffset);
        fbb.addOffset(4, pressureOffset);
        fbb.addOffset(5, temperatureOffset);
        fbb.addOffset(6, diameterOffset);
        fbb.addOffset(7, lengthOffset);
        fbb.addOffset(8, weightOffset);
        fbb.addOffset(9, adjustmentOffset);
        fbb.addOffset(10, dropOffset);
        fbb.addOffset(11, energyOffset);
        fbb.addOffset(12, sightHeightOffset);
        fbb.addOffset(13, twistOffset);
        fbb.addOffset(14, barrelLengthOffset);
        fbb.addOffset(15, timeOffset);
        fbb.addOffset(16, torqueOffset);
        fbb.addInt64(17, object.owner.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = UnitSettings()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..angular = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..distance = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..velocity = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..pressure = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..temperature = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..diameter = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..length = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '')
          ..weight = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..adjustment = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 22, '')
          ..drop = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 24, '')
          ..energy = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 26, '')
          ..sightHeight = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 28, '')
          ..twist = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 30, '')
          ..barrelLength = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 32, '')
          ..time = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 34, '')
          ..torque = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 36, '');
        object.owner.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          38,
          0,
        );
        object.owner.attach(store);
        return object;
      },
    ),
    Weapon: obx_int.EntityDefinition<Weapon>(
      model: _entities[8],
      toOneRelations: (Weapon object) => [object.owner],
      toManyRelations: (Weapon object) => {},
      getId: (Weapon object) => object.id,
      setId: (Weapon object, int id) {
        object.id = id;
      },
      objectToFB: (Weapon object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final vendorOffset = object.vendor == null
            ? null
            : fbb.writeString(object.vendor!);
        final imageOffset = object.image == null
            ? null
            : fbb.writeString(object.image!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.caliber);
        fbb.addFloat64(3, object.twist);
        fbb.addFloat64(4, object.barrelLength);
        fbb.addOffset(5, vendorOffset);
        fbb.addOffset(6, imageOffset);
        fbb.addInt64(7, object.owner.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Weapon()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..caliber = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..twist = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..barrelLength = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            12,
          )
          ..vendor = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 14)
          ..image = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 16);
        object.owner.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.owner.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Ammo] entity fields to define ObjectBox queries.
class Ammo_ {
  /// See [Ammo.id].
  static final id = obx.QueryIntegerProperty<Ammo>(_entities[0].properties[0]);

  /// See [Ammo.name].
  static final name = obx.QueryStringProperty<Ammo>(_entities[0].properties[1]);

  /// See [Ammo.caliber].
  static final caliber = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[2],
  );

  /// See [Ammo.weight].
  static final weight = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[3],
  );

  /// See [Ammo.length].
  static final length = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[4],
  );

  /// See [Ammo.dragTypeValue].
  static final dragTypeValue = obx.QueryStringProperty<Ammo>(
    _entities[0].properties[5],
  );

  /// See [Ammo.bcG1].
  static final bcG1 = obx.QueryDoubleProperty<Ammo>(_entities[0].properties[6]);

  /// See [Ammo.bcG7].
  static final bcG7 = obx.QueryDoubleProperty<Ammo>(_entities[0].properties[7]);

  /// See [Ammo.useMultiBcG1].
  static final useMultiBcG1 = obx.QueryBooleanProperty<Ammo>(
    _entities[0].properties[8],
  );

  /// See [Ammo.useMultiBcG7].
  static final useMultiBcG7 = obx.QueryBooleanProperty<Ammo>(
    _entities[0].properties[9],
  );

  /// See [Ammo.muzzleVelocity].
  static final muzzleVelocity = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[10],
  );

  /// See [Ammo.muzzleVelocityTemperature].
  static final muzzleVelocityTemperature = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[11],
  );

  /// See [Ammo.powderTemperature].
  static final powderTemperature = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[12],
  );

  /// See [Ammo.powderSensitivity].
  static final powderSensitivity = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[13],
  );

  /// See [Ammo.powderSensitivityTemperatures].
  static final powderSensitivityTemperatures =
      obx.QueryDoubleVectorProperty<Ammo>(_entities[0].properties[14]);

  /// See [Ammo.powderSensitivityVelocities].
  static final powderSensitivityVelocities =
      obx.QueryDoubleVectorProperty<Ammo>(_entities[0].properties[15]);

  /// See [Ammo.multiBcTableG1Mv].
  static final multiBcTableG1Mv = obx.QueryDoubleVectorProperty<Ammo>(
    _entities[0].properties[16],
  );

  /// See [Ammo.multiBcTableG1Bc].
  static final multiBcTableG1Bc = obx.QueryDoubleVectorProperty<Ammo>(
    _entities[0].properties[17],
  );

  /// See [Ammo.multiBcTableG7Mv].
  static final multiBcTableG7Mv = obx.QueryDoubleVectorProperty<Ammo>(
    _entities[0].properties[18],
  );

  /// See [Ammo.multiBcTableG7Bc].
  static final multiBcTableG7Bc = obx.QueryDoubleVectorProperty<Ammo>(
    _entities[0].properties[19],
  );

  /// See [Ammo.cusomDragTableV].
  static final cusomDragTableV = obx.QueryDoubleVectorProperty<Ammo>(
    _entities[0].properties[20],
  );

  /// See [Ammo.cusomDragTableCd].
  static final cusomDragTableCd = obx.QueryDoubleVectorProperty<Ammo>(
    _entities[0].properties[21],
  );

  /// See [Ammo.zeroDistance].
  static final zeroDistance = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[22],
  );

  /// See [Ammo.zeroLookAngle].
  static final zeroLookAngle = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[23],
  );

  /// See [Ammo.zeroTemperature].
  static final zeroTemperature = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[24],
  );

  /// See [Ammo.zeroPressure].
  static final zeroPressure = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[25],
  );

  /// See [Ammo.zeroHumidity].
  static final zeroHumidity = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[26],
  );

  /// See [Ammo.zeroPowdertemperature].
  static final zeroPowdertemperature = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[27],
  );

  /// See [Ammo.usePowderSensitivity].
  static final usePowderSensitivity = obx.QueryBooleanProperty<Ammo>(
    _entities[0].properties[28],
  );

  /// See [Ammo.zeroUseDiffPowderTemperature].
  static final zeroUseDiffPowderTemperature = obx.QueryBooleanProperty<Ammo>(
    _entities[0].properties[29],
  );

  /// See [Ammo.zeroUseCoriolis].
  static final zeroUseCoriolis = obx.QueryBooleanProperty<Ammo>(
    _entities[0].properties[30],
  );

  /// See [Ammo.zerolatitudeDeg].
  static final zerolatitudeDeg = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[31],
  );

  /// See [Ammo.zeroAzimuthDeg].
  static final zeroAzimuthDeg = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[32],
  );

  /// See [Ammo.zeroOffsetX].
  static final zeroOffsetX = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[33],
  );

  /// See [Ammo.zeroOffsetY].
  static final zeroOffsetY = obx.QueryDoubleProperty<Ammo>(
    _entities[0].properties[34],
  );

  /// See [Ammo.projectileName].
  static final projectileName = obx.QueryStringProperty<Ammo>(
    _entities[0].properties[35],
  );

  /// See [Ammo.vendor].
  static final vendor = obx.QueryStringProperty<Ammo>(
    _entities[0].properties[36],
  );

  /// See [Ammo.image].
  static final image = obx.QueryStringProperty<Ammo>(
    _entities[0].properties[37],
  );

  /// See [Ammo.owner].
  static final owner = obx.QueryRelationToOne<Ammo, Owner>(
    _entities[0].properties[38],
  );

  /// see [Ammo.profiles]
  static final profiles = obx.QueryBacklinkToMany<Profile, Ammo>(Profile_.ammo);
}

/// [ConvertorsState] entity fields to define ObjectBox queries.
class ConvertorsState_ {
  /// See [ConvertorsState.id].
  static final id = obx.QueryIntegerProperty<ConvertorsState>(
    _entities[1].properties[0],
  );

  /// See [ConvertorsState.lengthValueInch].
  static final lengthValueInch = obx.QueryDoubleProperty<ConvertorsState>(
    _entities[1].properties[1],
  );

  /// See [ConvertorsState.lengthUnit].
  static final lengthUnit = obx.QueryStringProperty<ConvertorsState>(
    _entities[1].properties[2],
  );

  /// See [ConvertorsState.weightValueGrain].
  static final weightValueGrain = obx.QueryDoubleProperty<ConvertorsState>(
    _entities[1].properties[3],
  );

  /// See [ConvertorsState.weight].
  static final weight = obx.QueryStringProperty<ConvertorsState>(
    _entities[1].properties[4],
  );

  /// See [ConvertorsState.pressureValueMmHg].
  static final pressureValueMmHg = obx.QueryDoubleProperty<ConvertorsState>(
    _entities[1].properties[5],
  );

  /// See [ConvertorsState.pressure].
  static final pressure = obx.QueryStringProperty<ConvertorsState>(
    _entities[1].properties[6],
  );

  /// See [ConvertorsState.temperatureValueFahrenheit].
  static final temperatureValueFahrenheit =
      obx.QueryDoubleProperty<ConvertorsState>(_entities[1].properties[7]);

  /// See [ConvertorsState.temperature].
  static final temperature = obx.QueryStringProperty<ConvertorsState>(
    _entities[1].properties[8],
  );

  /// See [ConvertorsState.torqueValueNewtonMeter].
  static final torqueValueNewtonMeter =
      obx.QueryDoubleProperty<ConvertorsState>(_entities[1].properties[9]);

  /// See [ConvertorsState.torque].
  static final torque = obx.QueryStringProperty<ConvertorsState>(
    _entities[1].properties[10],
  );

  /// See [ConvertorsState.anglesConvertorDistanceValueMeter].
  static final anglesConvertorDistanceValueMeter =
      obx.QueryDoubleProperty<ConvertorsState>(_entities[1].properties[11]);

  /// See [ConvertorsState.anglesConvertorDistance].
  static final anglesConvertorDistance =
      obx.QueryStringProperty<ConvertorsState>(_entities[1].properties[12]);

  /// See [ConvertorsState.anglesConvertorAngularValueMil].
  static final anglesConvertorAngularValueMil =
      obx.QueryDoubleProperty<ConvertorsState>(_entities[1].properties[13]);

  /// See [ConvertorsState.anglesConvertorAngular].
  static final anglesConvertorAngular =
      obx.QueryStringProperty<ConvertorsState>(_entities[1].properties[14]);

  /// See [ConvertorsState.anglesConvertorOutput].
  static final anglesConvertorOutput = obx.QueryStringProperty<ConvertorsState>(
    _entities[1].properties[15],
  );

  /// See [ConvertorsState.owner].
  static final owner = obx.QueryRelationToOne<ConvertorsState, Owner>(
    _entities[1].properties[16],
  );
}

/// [GeneralSettings] entity fields to define ObjectBox queries.
class GeneralSettings_ {
  /// See [GeneralSettings.id].
  static final id = obx.QueryIntegerProperty<GeneralSettings>(
    _entities[2].properties[0],
  );

  /// See [GeneralSettings.languageCode].
  static final languageCode = obx.QueryStringProperty<GeneralSettings>(
    _entities[2].properties[1],
  );

  /// See [GeneralSettings.themeMode].
  static final themeMode = obx.QueryStringProperty<GeneralSettings>(
    _entities[2].properties[2],
  );

  /// See [GeneralSettings.adjustmentDisplayFormatValue].
  static final adjustmentDisplayFormatValue =
      obx.QueryStringProperty<GeneralSettings>(_entities[2].properties[3]);

  /// See [GeneralSettings.homeShowMil].
  static final homeShowMil = obx.QueryBooleanProperty<GeneralSettings>(
    _entities[2].properties[4],
  );

  /// See [GeneralSettings.homeShowMrad].
  static final homeShowMrad = obx.QueryBooleanProperty<GeneralSettings>(
    _entities[2].properties[5],
  );

  /// See [GeneralSettings.homeShowMoa].
  static final homeShowMoa = obx.QueryBooleanProperty<GeneralSettings>(
    _entities[2].properties[6],
  );

  /// See [GeneralSettings.homeShowCmPer100m].
  static final homeShowCmPer100m = obx.QueryBooleanProperty<GeneralSettings>(
    _entities[2].properties[7],
  );

  /// See [GeneralSettings.homeShowInPer100yd].
  static final homeShowInPer100yd = obx.QueryBooleanProperty<GeneralSettings>(
    _entities[2].properties[8],
  );

  /// See [GeneralSettings.homeChartDistanceStep].
  static final homeChartDistanceStep = obx.QueryDoubleProperty<GeneralSettings>(
    _entities[2].properties[9],
  );

  /// See [GeneralSettings.homeTableDistanceStep].
  static final homeTableDistanceStep = obx.QueryDoubleProperty<GeneralSettings>(
    _entities[2].properties[10],
  );

  /// See [GeneralSettings.homeShowSubsonicTransition].
  static final homeShowSubsonicTransition =
      obx.QueryBooleanProperty<GeneralSettings>(_entities[2].properties[11]);

  /// See [GeneralSettings.activeProfile].
  static final activeProfile = obx.QueryRelationToOne<GeneralSettings, Profile>(
    _entities[2].properties[12],
  );

  /// See [GeneralSettings.owner].
  static final owner = obx.QueryRelationToOne<GeneralSettings, Owner>(
    _entities[2].properties[13],
  );
}

/// [Owner] entity fields to define ObjectBox queries.
class Owner_ {
  /// See [Owner.id].
  static final id = obx.QueryIntegerProperty<Owner>(_entities[3].properties[0]);

  /// See [Owner.token].
  static final token = obx.QueryStringProperty<Owner>(
    _entities[3].properties[1],
  );

  /// see [Owner.sights]
  static final sights = obx.QueryBacklinkToMany<Sight, Owner>(Sight_.owner);

  /// see [Owner.cartridges]
  static final cartridges = obx.QueryBacklinkToMany<Ammo, Owner>(Ammo_.owner);

  /// see [Owner.profiles]
  static final profiles = obx.QueryBacklinkToMany<Profile, Owner>(
    Profile_.owner,
  );

  /// see [Owner.generalSettings]
  static final generalSettings =
      obx.QueryBacklinkToMany<GeneralSettings, Owner>(GeneralSettings_.owner);

  /// see [Owner.unitSettings]
  static final unitSettings = obx.QueryBacklinkToMany<UnitSettings, Owner>(
    UnitSettings_.owner,
  );

  /// see [Owner.tablesSettings]
  static final tablesSettings = obx.QueryBacklinkToMany<TablesSettings, Owner>(
    TablesSettings_.owner,
  );

  /// see [Owner.convertorsState]
  static final convertorsState =
      obx.QueryBacklinkToMany<ConvertorsState, Owner>(ConvertorsState_.owner);
}

/// [Profile] entity fields to define ObjectBox queries.
class Profile_ {
  /// See [Profile.id].
  static final id = obx.QueryIntegerProperty<Profile>(
    _entities[4].properties[0],
  );

  /// See [Profile.name].
  static final name = obx.QueryStringProperty<Profile>(
    _entities[4].properties[1],
  );

  /// See [Profile.weapon].
  static final weapon = obx.QueryRelationToOne<Profile, Weapon>(
    _entities[4].properties[2],
  );

  /// See [Profile.sight].
  static final sight = obx.QueryRelationToOne<Profile, Sight>(
    _entities[4].properties[3],
  );

  /// See [Profile.ammo].
  static final ammo = obx.QueryRelationToOne<Profile, Ammo>(
    _entities[4].properties[4],
  );

  /// See [Profile.owner].
  static final owner = obx.QueryRelationToOne<Profile, Owner>(
    _entities[4].properties[5],
  );
}

/// [Sight] entity fields to define ObjectBox queries.
class Sight_ {
  /// See [Sight.id].
  static final id = obx.QueryIntegerProperty<Sight>(_entities[5].properties[0]);

  /// See [Sight.name].
  static final name = obx.QueryStringProperty<Sight>(
    _entities[5].properties[1],
  );

  /// See [Sight.focalPlaneValue].
  static final focalPlaneValue = obx.QueryStringProperty<Sight>(
    _entities[5].properties[2],
  );

  /// See [Sight.sightHeight].
  static final sightHeight = obx.QueryDoubleProperty<Sight>(
    _entities[5].properties[3],
  );

  /// See [Sight.verticalClick].
  static final verticalClick = obx.QueryDoubleProperty<Sight>(
    _entities[5].properties[4],
  );

  /// See [Sight.horizontalClick].
  static final horizontalClick = obx.QueryDoubleProperty<Sight>(
    _entities[5].properties[5],
  );

  /// See [Sight.verticalClickUnit].
  static final verticalClickUnit = obx.QueryStringProperty<Sight>(
    _entities[5].properties[6],
  );

  /// See [Sight.horizontalClickUnit].
  static final horizontalClickUnit = obx.QueryStringProperty<Sight>(
    _entities[5].properties[7],
  );

  /// See [Sight.sightHorizontalOffset].
  static final sightHorizontalOffset = obx.QueryDoubleProperty<Sight>(
    _entities[5].properties[8],
  );

  /// See [Sight.minMagnification].
  static final minMagnification = obx.QueryDoubleProperty<Sight>(
    _entities[5].properties[9],
  );

  /// See [Sight.maxMagnification].
  static final maxMagnification = obx.QueryDoubleProperty<Sight>(
    _entities[5].properties[10],
  );

  /// See [Sight.reticleImage].
  static final reticleImage = obx.QueryStringProperty<Sight>(
    _entities[5].properties[11],
  );

  /// See [Sight.vendor].
  static final vendor = obx.QueryStringProperty<Sight>(
    _entities[5].properties[12],
  );

  /// See [Sight.notes].
  static final notes = obx.QueryStringProperty<Sight>(
    _entities[5].properties[13],
  );

  /// See [Sight.image].
  static final image = obx.QueryStringProperty<Sight>(
    _entities[5].properties[14],
  );

  /// See [Sight.owner].
  static final owner = obx.QueryRelationToOne<Sight, Owner>(
    _entities[5].properties[15],
  );

  /// see [Sight.profiles]
  static final profiles = obx.QueryBacklinkToMany<Profile, Sight>(
    Profile_.sight,
  );
}

/// [TablesSettings] entity fields to define ObjectBox queries.
class TablesSettings_ {
  /// See [TablesSettings.id].
  static final id = obx.QueryIntegerProperty<TablesSettings>(
    _entities[6].properties[0],
  );

  /// See [TablesSettings.distanceStart].
  static final distanceStart = obx.QueryDoubleProperty<TablesSettings>(
    _entities[6].properties[1],
  );

  /// See [TablesSettings.distanceEnd].
  static final distanceEnd = obx.QueryDoubleProperty<TablesSettings>(
    _entities[6].properties[2],
  );

  /// See [TablesSettings.distanceStep].
  static final distanceStep = obx.QueryDoubleProperty<TablesSettings>(
    _entities[6].properties[3],
  );

  /// See [TablesSettings.showZeros].
  static final showZeros = obx.QueryBooleanProperty<TablesSettings>(
    _entities[6].properties[4],
  );

  /// See [TablesSettings.showSubsonicTransition].
  static final showSubsonicTransition =
      obx.QueryBooleanProperty<TablesSettings>(_entities[6].properties[5]);

  /// See [TablesSettings.hiddenCols].
  static final hiddenCols = obx.QueryStringVectorProperty<TablesSettings>(
    _entities[6].properties[6],
  );

  /// See [TablesSettings.hiddenAdjustmentCols].
  static final hiddenAdjustmentCols =
      obx.QueryStringVectorProperty<TablesSettings>(_entities[6].properties[7]);

  /// See [TablesSettings.owner].
  static final owner = obx.QueryRelationToOne<TablesSettings, Owner>(
    _entities[6].properties[8],
  );
}

/// [UnitSettings] entity fields to define ObjectBox queries.
class UnitSettings_ {
  /// See [UnitSettings.id].
  static final id = obx.QueryIntegerProperty<UnitSettings>(
    _entities[7].properties[0],
  );

  /// See [UnitSettings.angular].
  static final angular = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[1],
  );

  /// See [UnitSettings.distance].
  static final distance = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[2],
  );

  /// See [UnitSettings.velocity].
  static final velocity = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[3],
  );

  /// See [UnitSettings.pressure].
  static final pressure = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[4],
  );

  /// See [UnitSettings.temperature].
  static final temperature = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[5],
  );

  /// See [UnitSettings.diameter].
  static final diameter = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[6],
  );

  /// See [UnitSettings.length].
  static final length = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[7],
  );

  /// See [UnitSettings.weight].
  static final weight = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[8],
  );

  /// See [UnitSettings.adjustment].
  static final adjustment = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[9],
  );

  /// See [UnitSettings.drop].
  static final drop = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[10],
  );

  /// See [UnitSettings.energy].
  static final energy = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[11],
  );

  /// See [UnitSettings.sightHeight].
  static final sightHeight = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[12],
  );

  /// See [UnitSettings.twist].
  static final twist = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[13],
  );

  /// See [UnitSettings.barrelLength].
  static final barrelLength = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[14],
  );

  /// See [UnitSettings.time].
  static final time = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[15],
  );

  /// See [UnitSettings.torque].
  static final torque = obx.QueryStringProperty<UnitSettings>(
    _entities[7].properties[16],
  );

  /// See [UnitSettings.owner].
  static final owner = obx.QueryRelationToOne<UnitSettings, Owner>(
    _entities[7].properties[17],
  );
}

/// [Weapon] entity fields to define ObjectBox queries.
class Weapon_ {
  /// See [Weapon.id].
  static final id = obx.QueryIntegerProperty<Weapon>(
    _entities[8].properties[0],
  );

  /// See [Weapon.name].
  static final name = obx.QueryStringProperty<Weapon>(
    _entities[8].properties[1],
  );

  /// See [Weapon.caliber].
  static final caliber = obx.QueryDoubleProperty<Weapon>(
    _entities[8].properties[2],
  );

  /// See [Weapon.twist].
  static final twist = obx.QueryDoubleProperty<Weapon>(
    _entities[8].properties[3],
  );

  /// See [Weapon.barrelLength].
  static final barrelLength = obx.QueryDoubleProperty<Weapon>(
    _entities[8].properties[4],
  );

  /// See [Weapon.vendor].
  static final vendor = obx.QueryStringProperty<Weapon>(
    _entities[8].properties[5],
  );

  /// See [Weapon.image].
  static final image = obx.QueryStringProperty<Weapon>(
    _entities[8].properties[6],
  );

  /// See [Weapon.owner].
  static final owner = obx.QueryRelationToOne<Weapon, Owner>(
    _entities[8].properties[7],
  );
}
