// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'src/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 927865793517048258),
    name: 'Profile',
    lastPropertyId: const obx_int.IdUid(2, 6920431302249106786),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1712378980982867402),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6920431302249106786),
        name: 'sightId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 6834864895426136447),
        relationField: 'sight',
        relationTarget: 'Sight',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8108854136363241544),
    name: 'Sight',
    lastPropertyId: const obx_int.IdUid(14, 5914095292417277866),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9029637454336908641),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3922188448057528623),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 8600855167308690224),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7454543858181517435),
        name: 'vendor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1782686891491927631),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4158128972074747949),
        name: 'sightHeight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1904073500009616213),
        name: 'verticalClick',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3936752266638878961),
        name: 'horizontalClick',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4057660476111248037),
        name: 'verticalClickUnit',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8114619133304734877),
        name: 'horizontalClickUnit',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8979097063658358113),
        name: 'sightHorizontalOffset',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 446448943120464622),
        name: 'minMagnification',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2654570214217167529),
        name: 'maxMagnification',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1103348764861245392),
        name: 'reticleImage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5914095292417277866),
        name: 'focalPlaneValue',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'profiles',
        srcEntity: 'Profile',
        srcField: 'sight',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 8108854136363241544),
    lastIndexId: const obx_int.IdUid(2, 8600855167308690224),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Profile: obx_int.EntityDefinition<Profile>(
      model: _entities[0],
      toOneRelations: (Profile object) => [object.sight],
      toManyRelations: (Profile object) => {},
      getId: (Profile object) => object.id,
      setId: (Profile object, int id) {
        object.id = id;
      },
      objectToFB: (Profile object, fb.Builder fbb) {
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.sight.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Profile()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.sight.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.sight.attach(store);
        return object;
      },
    ),
    Sight: obx_int.EntityDefinition<Sight>(
      model: _entities[1],
      toOneRelations: (Sight object) => [],
      toManyRelations: (Sight object) => {
        obx_int.RelInfo<Profile>.toOneBacklink(
          2,
          object.id,
          (Profile srcObject) => srcObject.sight,
        ): object.profiles,
      },
      getId: (Sight object) => object.id,
      setId: (Sight object, int id) {
        object.id = id;
      },
      objectToFB: (Sight object, fb.Builder fbb) {
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final vendorOffset = object.vendor == null
            ? null
            : fbb.writeString(object.vendor!);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final verticalClickUnitOffset = object.verticalClickUnit == null
            ? null
            : fbb.writeString(object.verticalClickUnit!);
        final horizontalClickUnitOffset = object.horizontalClickUnit == null
            ? null
            : fbb.writeString(object.horizontalClickUnit!);
        final reticleImageOffset = object.reticleImage == null
            ? null
            : fbb.writeString(object.reticleImage!);
        final focalPlaneValueOffset = object.focalPlaneValue == null
            ? null
            : fbb.writeString(object.focalPlaneValue!);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, vendorOffset);
        fbb.addOffset(3, notesOffset);
        fbb.addFloat64(4, object.sightHeight);
        fbb.addFloat64(5, object.verticalClick);
        fbb.addFloat64(6, object.horizontalClick);
        fbb.addOffset(7, verticalClickUnitOffset);
        fbb.addOffset(8, horizontalClickUnitOffset);
        fbb.addFloat64(9, object.sightHorizontalOffset);
        fbb.addFloat64(10, object.minMagnification);
        fbb.addFloat64(11, object.maxMagnification);
        fbb.addOffset(12, reticleImageOffset);
        fbb.addOffset(13, focalPlaneValueOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final horizontalClickParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final verticalClickParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final verticalClickUnitParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final horizontalClickUnitParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final sightHeightParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final sightHorizontalOffsetParam = const fb.Float64Reader()
            .vTableGetNullable(buffer, rootOffset, 22);
        final minMagnificationParam = const fb.Float64Reader()
            .vTableGetNullable(buffer, rootOffset, 24);
        final maxMagnificationParam = const fb.Float64Reader()
            .vTableGetNullable(buffer, rootOffset, 26);
        final reticleImageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final vendorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object =
            Sight(
                name: nameParam,
                horizontalClick: horizontalClickParam,
                verticalClick: verticalClickParam,
                verticalClickUnit: verticalClickUnitParam,
                horizontalClickUnit: horizontalClickUnitParam,
                sightHeight: sightHeightParam,
                sightHorizontalOffset: sightHorizontalOffsetParam,
                minMagnification: minMagnificationParam,
                maxMagnification: maxMagnificationParam,
                reticleImage: reticleImageParam,
                vendor: vendorParam,
                notes: notesParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..focalPlaneValue = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 30);
        obx_int.InternalToManyAccess.setRelInfo<Sight>(
          object.profiles,
          store,
          obx_int.RelInfo<Profile>.toOneBacklink(
            2,
            object.id,
            (Profile srcObject) => srcObject.sight,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Profile] entity fields to define ObjectBox queries.
class Profile_ {
  /// See [Profile.id].
  static final id = obx.QueryIntegerProperty<Profile>(
    _entities[0].properties[0],
  );

  /// See [Profile.sight].
  static final sight = obx.QueryRelationToOne<Profile, Sight>(
    _entities[0].properties[1],
  );
}

/// [Sight] entity fields to define ObjectBox queries.
class Sight_ {
  /// See [Sight.id].
  static final id = obx.QueryIntegerProperty<Sight>(_entities[1].properties[0]);

  /// See [Sight.name].
  static final name = obx.QueryStringProperty<Sight>(
    _entities[1].properties[1],
  );

  /// See [Sight.vendor].
  static final vendor = obx.QueryStringProperty<Sight>(
    _entities[1].properties[2],
  );

  /// See [Sight.notes].
  static final notes = obx.QueryStringProperty<Sight>(
    _entities[1].properties[3],
  );

  /// See [Sight.sightHeight].
  static final sightHeight = obx.QueryDoubleProperty<Sight>(
    _entities[1].properties[4],
  );

  /// See [Sight.verticalClick].
  static final verticalClick = obx.QueryDoubleProperty<Sight>(
    _entities[1].properties[5],
  );

  /// See [Sight.horizontalClick].
  static final horizontalClick = obx.QueryDoubleProperty<Sight>(
    _entities[1].properties[6],
  );

  /// See [Sight.verticalClickUnit].
  static final verticalClickUnit = obx.QueryStringProperty<Sight>(
    _entities[1].properties[7],
  );

  /// See [Sight.horizontalClickUnit].
  static final horizontalClickUnit = obx.QueryStringProperty<Sight>(
    _entities[1].properties[8],
  );

  /// See [Sight.sightHorizontalOffset].
  static final sightHorizontalOffset = obx.QueryDoubleProperty<Sight>(
    _entities[1].properties[9],
  );

  /// See [Sight.minMagnification].
  static final minMagnification = obx.QueryDoubleProperty<Sight>(
    _entities[1].properties[10],
  );

  /// See [Sight.maxMagnification].
  static final maxMagnification = obx.QueryDoubleProperty<Sight>(
    _entities[1].properties[11],
  );

  /// See [Sight.reticleImage].
  static final reticleImage = obx.QueryStringProperty<Sight>(
    _entities[1].properties[12],
  );

  /// See [Sight.focalPlaneValue].
  static final focalPlaneValue = obx.QueryStringProperty<Sight>(
    _entities[1].properties[13],
  );

  /// see [Sight.profiles]
  static final profiles = obx.QueryBacklinkToMany<Profile, Sight>(
    Profile_.sight,
  );
}
