import 'package:bclibc_ffi/unit.dart';
import 'package:ebalistyka/l10n/app_localizations.dart';

extension UnitLocalizationExtension on Unit {
  String localizedLabel(AppLocalizations l10n) => switch (this) {
    Unit.millimeter => l10n.unitMillimeters,
    Unit.centimeter => l10n.unitCentimeters,
    Unit.meter => l10n.unitMeters,
    Unit.inch => l10n.unitInches,
    Unit.foot => l10n.unitFeet,
    Unit.yard => l10n.unitYards,
    Unit.grain => l10n.unitGrains,
    Unit.gram => l10n.unitGrams,
    Unit.kilogram => l10n.unitKilograms,
    Unit.pound => l10n.unitPounds,
    Unit.ounce => l10n.unitOunces,
    Unit.mps => l10n.unitMps,
    Unit.fps => l10n.unitFps,
    Unit.kmh => l10n.unitKmh,
    Unit.mph => l10n.unitMph,
    Unit.mach => l10n.unitMach,
    Unit.celsius => l10n.unitCelsius,
    Unit.fahrenheit => l10n.unitFahrenheit,
    Unit.hPa => l10n.unitHPa,
    Unit.mmHg => l10n.unitMmHg,
    Unit.inHg => l10n.unitInHg,
    Unit.bar => l10n.unitBar,
    Unit.psi => l10n.unitPsi,
    Unit.atm => l10n.unitAtmosphere,
    Unit.joule => l10n.unitJoule,
    Unit.footPound => l10n.unitFootPound,
    Unit.footPoundTorque => l10n.unitFootPound,
    Unit.newtonMeter => l10n.unitNewtonMeter,
    Unit.inchPound => l10n.unitInchPound,
    Unit.mil => l10n.unitMil,
    Unit.moa => l10n.unitMoa,
    Unit.mRad => l10n.unitMrad,
    Unit.cmPer100m => l10n.unitCmPer100m,
    Unit.inPer100Yd => l10n.unitInPer100Yd,
    Unit.degree => l10n.unitDegrees,
    _ => label,
  };

  String localizedSymbol(AppLocalizations l10n) => switch (this) {
    Unit.millimeter => l10n.unitMillimeterSym,
    Unit.centimeter => l10n.unitCentimeterSym,
    Unit.meter => l10n.unitMeterSym,
    Unit.inch => l10n.unitInchSym,
    Unit.foot => l10n.unitFootSym,
    Unit.yard => l10n.unitYardSym,
    Unit.grain => l10n.unitGrainSym,
    Unit.gram => l10n.unitGramSym,
    Unit.kilogram => l10n.unitKilogramSym,
    Unit.pound => l10n.unitPoundSym,
    Unit.ounce => l10n.unitOunceSym,
    Unit.mps => l10n.unitMpsSym,
    Unit.fps => l10n.unitFpsSym,
    Unit.kmh => l10n.unitKmhSym,
    Unit.mph => l10n.unitMphSym,
    Unit.mach => l10n.unitMachSym,
    Unit.celsius => l10n.unitCelsiusSym,
    Unit.fahrenheit => l10n.unitFahrenheitSym,
    Unit.hPa => l10n.unitHPaSym,
    Unit.mmHg => l10n.unitMmHgSym,
    Unit.inHg => l10n.unitInHgSym,
    Unit.bar => l10n.unitBarSym,
    Unit.psi => l10n.unitPsiSym,
    Unit.atm => l10n.unitAtmSym,
    Unit.joule => l10n.unitJouleSym,
    Unit.footPound => l10n.unitFootPoundSym,
    Unit.footPoundTorque => l10n.unitFootPoundSym,
    Unit.newtonMeter => l10n.unitNewtonMeterSym,
    Unit.inchPound => l10n.unitInchPoundSym,
    Unit.mil => l10n.unitMilSym,
    Unit.moa => l10n.unitMoaSym,
    Unit.mRad => l10n.unitMradSym,
    Unit.cmPer100m => l10n.unitCmPer100mSym,
    Unit.inPer100Yd => l10n.unitInPer100YdSym,
    Unit.degree => l10n.unitDegreesSym,
    _ => symbol,
  };
}
